### ISSUE TITLE
如何跑nuscene数据？

### ISSUE THREAD

**Issue by rockywind** [megvii-research/Far3D#1]
您好，感谢开源，
现在生成了nuscene的pkl, 我看config里面是argoverse的，我改如何跑nuscene数据，方便解答一下，十分感谢！

**Comment by xhjiang-pixel** [comment]
您好，如果还需要的话请提供一下您的邮箱，我可以把config发给您参考。

**Comment by rockywind** [comment]
您好，太感谢了，这是我的邮箱：rockywindwang@gmail.com

**Comment by AlmoonYsl** [comment]
> 您好，如果还需要的话请提供一下您的邮箱，我可以把config发给您参考。

您好，可以也给我提供一份Far3D在nuScenes上的config吗，这是我的邮箱：jhhou@hust.edu.cn，谢谢。

**Comment by fufuwudi** [comment]
您好，我也想评测一下，FAR3D在Nuscenes上的效果。可以提供一下config么，这是我的邮箱2038566273@qq,com

**Comment by vehxianfish** [comment]
> 您好，太感谢了，这是我的邮箱：[rockywindwang@gmail.com](mailto:rockywindwang@gmail.com)


您好，方便发一份nuscense的config文件吗？ 感谢. 邮箱为s_xu@foxmail.com
@xhjiang-pixel @rockywind

**Comment by RicePasteM** [comment]
Hi, could you share a copy with me? [HuZhangchi@mail.ustc.edu.cn](HuZhangchi@mail.ustc.edu.cn)
Thanks a lot!!!!

**Comment by iiiiiikou** [comment]
您好，我想复现一下，Far3D在Nuscenes上的效果。可以提供一下config么，这是我的邮箱08213138@cumt.edu.cn

**Comment by suyu-star** [comment]
您好，我也想复现一下NuScenes上的效果，能否提供一下config文件，十分感谢779721003@qq.com


> 您好，如果还需要的话请提供一下您的邮箱，我可以把config发给您参考。

**Comment by clever-mood** [comment]
> 您好，太感谢了，这是我的邮箱：[rockywindwang@gmail.com](mailto:rockywindwang@gmail.com)

您好，请问您收到了nuscenes数据集上的config文件了吗？不知您是否愿意分享一下，我的邮箱是：525097426@qq.com。非常感谢！

**Comment by clever-mood** [comment]
> 您好，我想复现一下，Far3D在Nuscenes上的效果。可以提供一下config么，这是我的邮箱[08213138@cumt.edu.cn](mailto:08213138@cumt.edu.cn)

您好，请问您收到了nuscenes数据集上的config文件了吗？不知您是否愿意分享一下，我的邮箱是：[525097426@qq.com](mailto:525097426@qq.com)。非常感谢！

**Comment by clever-mood** [comment]
> Hi, could you share a copy with me? [HuZhangchi@mail.ustc.edu.cn](HuZhangchi@mail.ustc.edu.cn) Thanks a lot!!!!

您好，请问您收到了nuscenes数据集上的config文件了吗？不知您是否愿意分享一下，我的邮箱是：[525097426@qq.com](mailto:525097426@qq.com)。非常感谢！

**Comment by RicePasteM** [comment]
> > Hi, could you share a copy with me? [HuZhangchi@mail.ustc.edu.cn](HuZhangchi@mail.ustc.edu.cn) Thanks a lot!!!!
> 
> 您好，请问您收到了nuscenes数据集上的config文件了吗？不知您是否愿意分享一下，我的邮箱是：[525097426@qq.com](mailto:525097426@qq.com)。非常感谢！

你好，目前没有收到作者的回复，我已经放弃复现这个项目，你可以参考CVPR的几篇和这个类似的工作。

**Comment by suyu-star** [comment]
好的，十分感谢



---原始邮件---
发件人: "Zhangchi ***@***.***&gt;
发送时间: 2025年3月12日(周三) 中午12:43
收件人: ***@***.***&gt;;
抄送: "sucessfully ***@***.******@***.***&gt;;
主题: Re: [megvii-research/Far3D] 如何跑nuscene数据？ (Issue #1)


     
Hi, could you share a copy with me? ***@***.*** Thanks a lot!!!!
  
***@***.***。非常感谢！
  
你好，目前没有收到作者的回复，我已经放弃复现这个项目，你可以参考CVPR的几篇和这个类似的工作。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  RicePasteM left a comment (megvii-research/Far3D#1)
   
Hi, could you share a copy with me? ***@***.*** Thanks a lot!!!!
  
***@***.***。非常感谢！
  
你好，目前没有收到作者的回复，我已经放弃复现这个项目，你可以参考CVPR的几篇和这个类似的工作。

**Comment by ddsaplus** [comment]
> 您好，如果还需要的话请提供一下您的邮箱，我可以把配置发给您参考。

您好，请问能否分享一份给我的配置吗，非常感谢，我的邮箱：[cuiforwork@hnu.edu.cn](mailto:cuiforwork@hnu.edu.cn)

**Comment by 670160532lileilei-wq** [comment]
> 您好，如果还需要的话请提供一下您的邮箱，我可以把config发给您参考。

您好，还方便发一份nuscense的config文件吗？ 感谢. 邮箱670160532@qq.com
